server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_booking
spring.datasource.username=admin
spring.datasource.password=venkat791
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
spring.liquibase.enabled=true

jwt.secret=your_super_secret_key_must_be_at_least_256_bits_long
jwt.expiration=86400000